

CREATE TABLE TBL_TESTMEMBER(
	TESTMEMBER_ID NUMBER CONSTRAINT PK_TESTMEMBER PRIMARY KEY,
	TESTMEMBER_IDENTIFICATION VARCHAR2(500) UNIQUE NOT NULL,
	TESTMEMBER_PASSWORD VARCHAR2(500) NOT NULL,
	TESTMEMBER_NAME VARCHAR2(500) NOT NULL,
	TESTMEMBER_PHONE VARCHAR2(500) NOT NULL,
	TESTMEMBER_NICKNAME VARCHAR2(500),
	TESTMEMBER_EMAIL VARCHAR2(500) NOT NULL,
	TESTMEMBER_ADDRESS VARCHAR2(500),
	TESTMEMBER_BIRTH DATE,
	TESTMEMBER_RECOMMENDER_ID VARCHAR2(500)
);

SELECT * FROM TBL_TESTMEMBER;
