/*회원 테이블 생성*/

CREATE SEQUENCE SEQ_MEMBER;

CREATE TABLE TBL_MEMBER(
	ID NUMBER CONSTRAINT PK_MEMBER PRIMARY KEY,
	MEMBER_ID VARCHAR2(1000) UNIQUE NOT NULL,
	MEMBER_PASSWORD VARCHAR2(1000) NOT NULL,
	MEMBER_NAME VARCHAR2(1000) NOT NULL,
	MEMBER_NICKNAME VARCHAR2(1000) NOT NULL,
	MEMBER_PHONE_NUMBER VARCHAR2(1000) NOT NULL,
	MEMBER_STATUS CHAR(1) DEFAULT '1' CONSTRAINT CHECK_MEMBER_STATUS 
	CHECK(MEMBER_STATUS IN ('0', '1')),
	MEMBER_GRADE VARCHAR2(500) DEFAULT 'USER' CONSTRAINT CHECK_MEMBER_GRADE
	CHECK(MEMBER_GRADE IN ('ADMIN', 'USER')),
	MEMBER_POINT NUMBER DEFAULT 2000,
	MEMBER_SCHOOL VARCHAR2(1000),
	MEMBER_MAJOR VARCHAR2(1000),
	MEMBER_INTRODUCING VARCHAR2(1000),
	MEMBER_LOGIN_STATUS VARCHAR2(1000) DEFAULT 'WEGETHER' CONSTRAINT CHECK_MEMBER_LOGIN_STATUS
	CHECK(MEMBER_LOGIN_STATUS IN ('WEGETHER', 'KAKAO', 'NAVER')),
	FILE_PATH VARCHAR2(1000),
	FILE_UUID VARCHAR2(1000),
	FILE_NAME VARCHAR2(1000),
	FILE_SIZE NUMBER,
	SNS_PROFILE VARCHAR2(1000),
	MEMBER_REGISTER_DATE DATE DEFAULT SYSDATE,
	MEMBER_UPDATE_DATE DATE DEFAULT SYSDATE
);

SELECT * FROM TBL_MEMBER;

DROP TABLE TBL_MEMBER;