/*답변 테이블 생성*/

CREATE SEQUENCE SEQ_ANSWER;

CREATE TABLE TBL_ANSWER(
	ID NUMBER CONSTRAINT PK_ANSWER PRIMARY KEY,
	INQUIRY_ID NUMBER NOT NULL,
	ANSWER_CONTENT VARCHAR2(1000) NOT NULL,
	ANSWER_REGISTER_DATE DATE DEFAULT SYSDATE,
	ANSWER_UPDATE_DATE DATE DEFAULT SYSDATE
);

SELECT * FROM TBL_ANSWER;

DROP TABLE TBL_ANSWER;

/*TBL_ANSWER 테이블 FK 설정*/
	ALTER TABLE TBL_ANSWER ADD CONSTRAINT FK_ANSWER_INQUIRY FOREIGN KEY(INQUIRY_ID)
	REFERENCES TBL_INQUIRY(ID);