/*카드 등록 테이블 생성*/

CREATE SEQUENCE SEQ_CARD;

CREATE TABLE TBL_CARD(
	ID NUMBER CONSTRAINT PK_CARD PRIMARY KEY,
	MEMBER_ID NUMBER NOT NULL,
	CARD_NUMBER VARCHAR2(1000) NOT NULL,
	CARD_BIRTH_DATE VARCHAR2(1000) NOT NULL,
	MEMBER_BIRTH_DATE VARCHAR2(1000) NOT NULL,
	CARD_PASSWORD VARCHAR2(1000) NOT NULL,
	CARD_REGISTER_DATE DATE DEFAULT SYSDATE
);

SELECT * FROM TBL_CARD;

DROP TABLE TBL_CARD;

/*TBL_CARD 테이블 FK 설정*/
	ALTER TABLE TBL_CARD ADD CONSTRAINT FK_CARD_MEMBER FOREIGN KEY(MEMBER_ID)
	REFERENCES TBL_MEMBER(ID);