/*커뮤니티 테이블 생성*/

CREATE SEQUENCE SEQ_COMMUNITY;

CREATE TABLE TBL_COMMUNITY(
	ID NUMBER CONSTRAINT PK_COMMUNITY PRIMARY KEY,
	MEMBER_ID NUMBER NOT NULL,
	COMMUNITY_TITLE VARCHAR2(1000) NOT NULL,
	COMMUNITY_SUBTITLE VARCHAR2(1000) NOT NULL,
	COMMUNITY_CONTENT VARCHAR2(1000) NOT NULL,
	COMMUNITY_REGISTER_DATE DATE DEFAULT SYSDATE,
	COMMUNITY_UPDATE_DATE DATE DEFAULT SYSDATE
);

SELECT * FROM TBL_COMMUNITY;

DROP TABLE TBL_COMMUNITY;

/*TBL_COMMUNITY 테이블 FK 설정*/
	ALTER TABLE TBL_COMMUNITY ADD CONSTRAINT FK_COMMUNITY_MEMBER FOREIGN KEY(MEMBER_ID)
	REFERENCES TBL_MEMBER(ID);


