/*강연 파일 테이블 생성*/

CREATE SEQUENCE SEQ_LECTURE_FILE;

CREATE TABLE TBL_LECTURE_FILE(
	ID NUMBER CONSTRAINT PK_LECTURE_FILE PRIMARY KEY,
	LECTURE_ID NUMBER NOT NULL
);

SELECT * FROM TBL_LECTURE;

DROP TABLE TBL_LECTURE_FILE;

/*TBL_LECTURE_FILE 테이블 FK 설정*/
	ALTER TABLE TBL_LECTURE_FILE ADD CONSTRAINT FK_LECTURE_FILE_FILE FOREIGN KEY(ID)
	REFERENCES TBL_FILE(ID);
	
	ALTER TABLE TBL_LECTURE_FILE ADD CONSTRAINT FK_LECTURE_FILE_LECTURE FOREIGN KEY(LECTURE_ID)
	REFERENCES TBL_LECTURE(ID);
