/*파일 테이블 생성*/

CREATE SEQUENCE SEQ_FILE;

CREATE TABLE TBL_FILE(
	ID NUMBER CONSTRAINT PK_FILE PRIMARY KEY,
	FILE_PATH VARCHAR2(1000) NOT NULL,
	FILE_UUID VARCHAR2(1000) NOT NULL,
	FILE_NAME VARCHAR2(1000) NOT NULL,
	FILE_SIZE NUMBER NOT NULL,
	FILE_TYPE VARCHAR2(1000) DEFAULT 'NON_REPRESENTATIVE'
	CONSTRAINT CHECK_FILE_TYPE CHECK(FILE_TYPE IN ('NON_REPRESENTATIVE', 'REPRESENTATIVE'))
);

SELECT * FROM TBL_FILE;

DROP TABLE TBL_FILE;

-------------------------------------------------------- TBL_FILE -----------------------------------------------------

INSERT INTO WEGETHER.TBL_FILE
(ID, FILE_PATH, FILE_UUID, FILE_NAME, FILE_SIZE, FILE_TYPE)
VALUES(1101   ,'2023/05/31', 'id', '프로젝트1.png', 0, 'REPRESENTATIVE')

INSERT INTO WEGETHER.TBL_FILE
(ID, FILE_PATH, FILE_UUID, FILE_NAME, FILE_SIZE, FILE_TYPE)
VALUES(1102   ,'2023/05/31', 'id', '프로젝트2.png', 0, 'REPRESENTATIVE')

INSERT INTO WEGETHER.TBL_FILE
(ID, FILE_PATH, FILE_UUID, FILE_NAME, FILE_SIZE, FILE_TYPE)
VALUES(1103   ,'2023/05/31', 'id', '프로젝트3.png', 0, 'REPRESENTATIVE')

INSERT INTO WEGETHER.TBL_FILE
(ID, FILE_PATH, FILE_UUID, FILE_NAME, FILE_SIZE, FILE_TYPE)
VALUES(1104   ,'2023/05/31', 'id', '프로젝트4.png', 0, 'REPRESENTATIVE')

INSERT INTO WEGETHER.TBL_FILE
(ID, FILE_PATH, FILE_UUID, FILE_NAME, FILE_SIZE, FILE_TYPE)
VALUES(1105   ,'2023/05/31', 'id', '프로젝트5.png', 0, 'REPRESENTATIVE')

INSERT INTO WEGETHER.TBL_FILE
(ID, FILE_PATH, FILE_UUID, FILE_NAME, FILE_SIZE, FILE_TYPE)
VALUES(1106   ,'2023/05/31', 'id', '프로젝트6.png', 0, 'REPRESENTATIVE')

INSERT INTO WEGETHER.TBL_FILE
(ID, FILE_PATH, FILE_UUID, FILE_NAME, FILE_SIZE, FILE_TYPE)
VALUES(1107   ,'2023/05/31', 'id', '프로젝트7.png', 0, 'REPRESENTATIVE')

INSERT INTO WEGETHER.TBL_FILE
(ID, FILE_PATH, FILE_UUID, FILE_NAME, FILE_SIZE, FILE_TYPE)
VALUES(1108   ,'2023/05/31', 'id', '프로젝트8.png', 0, 'REPRESENTATIVE')

INSERT INTO WEGETHER.TBL_FILE
(ID, FILE_PATH, FILE_UUID, FILE_NAME, FILE_SIZE, FILE_TYPE)
VALUES(1109   ,'2023/05/31', 'id', '프로젝트9.png', 0, 'REPRESENTATIVE')

INSERT INTO WEGETHER.TBL_FILE
(ID, FILE_PATH, FILE_UUID, FILE_NAME, FILE_SIZE, FILE_TYPE)
VALUES(1110   ,'2023/05/31', 'id', '프로젝트10.png', 0, 'REPRESENTATIVE')

SELECT * FROM TBL_FILE


