/*커뮤니티 파일 테이블 생성*/

CREATE SEQUENCE SEQ_COMMUNITY_FILE;

CREATE TABLE TBL_COMMUNITY_FILE(
	ID NUMBER CONSTRAINT PK_COMMUNITY_FILE PRIMARY KEY,
	COMMUNITY_ID NUMBER NOT NULL
);

SELECT * FROM TBL_COMMUNITY_FILE;

DROP TABLE TBL_COMMUNITY_FILE;

/*TBL_COMMUNITY_FILE 테이블 FK 설정*/
	ALTER TABLE TBL_COMMUNITY_FILE ADD CONSTRAINT FK_COMMUNITY_FILE_FILE FOREIGN KEY(ID)
	REFERENCES TBL_FILE(ID);

	ALTER TABLE TBL_COMMUNITY_FILE ADD CONSTRAINT FK_COMMUNITY_FILE_COMMUNITY FOREIGN KEY(COMMUNITY_ID)
	REFERENCES TBL_COMMUNITY(ID);
