/*강연 테이블 생성*/

CREATE SEQUENCE SEQ_LECTURE;

CREATE TABLE TBL_LECTURE(
	ID NUMBER CONSTRAINT PK_LECTURE PRIMARY KEY,
	LECTURE_TITLE VARCHAR2(1000) NOT NULL,
	LECTURE_CONTENT VARCHAR2(1000) NOT NULL,
	LECTURE_DATE VARCHAR2(1000) NOT NULL,
	LECTURE_TIME VARCHAR2(1000) NOT NULL,
	LECTURE_LOCATION VARCHAR2(1000) NOT NULL,
	LECTURE_TOTAL_PERSONNEL NUMBER NOT NULL,
	LECTURE_REGISTER_DATE DATE DEFAULT SYSDATE,
	LECTURE_UPDATE_DATE DATE DEFAULT SYSDATE
);

SELECT * FROM TBL_LECTURE;

DROP TABLE TBL_LECTURE;