/*공지사항 파일 테이블 생성*/

CREATE SEQUENCE SEQ_NOTICE_FILE;

CREATE TABLE TBL_NOTICE_FILE(
	ID NUMBER CONSTRAINT PK_NOTICE_FILE PRIMARY KEY,
	NOTICE_ID NUMBER NOT NULL
);

SELECT * FROM TBL_NOTICE_FILE;

DROP TABLE TBL_NOTICE_FILE;


/*TBL_NOTICE_FILE 테이블 FK 설정*/
	ALTER TABLE TBL_NOTICE_FILE ADD CONSTRAINT FK_NOTICE_FILE_FILE FOREIGN KEY(ID)
	REFERENCES TBL_FILE(ID);
	
	ALTER TABLE TBL_NOTICE_FILE ADD CONSTRAINT FK_NOTICE_FILE_NOTICE FOREIGN KEY(NOTICE_ID)
	REFERENCES TBL_NOTICE(ID);