/*프로젝트 파일 테이블 생성*/

CREATE SEQUENCE SEQ_PROJECT_FILE;

CREATE TABLE TBL_PROJECT_FILE(
	ID NUMBER CONSTRAINT PK_PROJECT_FILE PRIMARY KEY,
	PROJECT_ID NUMBER NOT NULL
);

SELECT * FROM TBL_PROJECT_FILE;

DROP TABLE TBL_PROJECT_FILE;

/*TBL_PROJECT_FILE 테이블 FK 설정*/
	ALTER TABLE TBL_PROJECT_FILE ADD CONSTRAINT FK_PROJECT_FILE_FILE FOREIGN KEY(ID)
	REFERENCES TBL_FILE(ID);

	ALTER TABLE TBL_PROJECT_FILE ADD CONSTRAINT FK_PROJECT_FILE_PROJECT FOREIGN KEY(PROJECT_ID)
	REFERENCES TBL_PROJECT(ID);

----------------------------------------------------- TBL_PROJECT_FILE --------------------------------------------------


INSERT INTO WEGETHER.TBL_PROJECT_FILE
(ID, PROJECT_ID)
VALUES(1101, 123);

INSERT INTO WEGETHER.TBL_PROJECT_FILE
(ID, PROJECT_ID)
VALUES(1102, 124);

INSERT INTO WEGETHER.TBL_PROJECT_FILE
(ID, PROJECT_ID)
VALUES(1103, 125);

INSERT INTO WEGETHER.TBL_PROJECT_FILE
(ID, PROJECT_ID)
VALUES(1104, 126);

INSERT INTO WEGETHER.TBL_PROJECT_FILE
(ID, PROJECT_ID)
VALUES(1105, 127);

INSERT INTO WEGETHER.TBL_PROJECT_FILE
(ID, PROJECT_ID)
VALUES(1106, 128);

INSERT INTO WEGETHER.TBL_PROJECT_FILE
(ID, PROJECT_ID)
VALUES(1107, 129);

INSERT INTO WEGETHER.TBL_PROJECT_FILE
(ID, PROJECT_ID)
VALUES(1108, 130);

INSERT INTO WEGETHER.TBL_PROJECT_FILE
(ID, PROJECT_ID)
VALUES(1109, 131);

INSERT INTO WEGETHER.TBL_PROJECT_FILE
(ID, PROJECT_ID)
VALUES(1110, 132);
