/*프로젝트 테이블 생성*/
CREATE SEQUENCE SEQ_PROJECT;

DROP TABLE TBL_PROJECT;

CREATE TABLE TBL_PROJECT(
	ID NUMBER CONSTRAINT PK_PROJECT PRIMARY KEY,
	MEMBER_ID NUMBER NOT NULL,
	PROJECT_TITLE VARCHAR2(1000) NOT NULL,
	PROJECT_INTRODUCING VARCHAR2(1000) NOT NULL,
	PROJECT_SCHOOL VARCHAR2(1000) NOT NULL,
	PROJECT_MAJOR VARCHAR2(1000) NOT NULL,
	PROJECT_END_DATE VARCHAR2(1000) NOT NULL,
	PROJECT_READ_COUNT NUMBER DEFAULT 0,
	PROJECT_NOW_PERSONNEL NUMBER DEFAULT 0,
	PROJECT_TOTAL_PERSONNEL NUMBER NOT NULL,
	PROJECT_REGISTER_DATE DATE DEFAULT SYSDATE,
	PROJECT_UPDATE_DATE DATE DEFAULT SYSDATE
);

SELECT * FROM TBL_PROJECT;

/*TBL_PROJECT 테이블 FK 설정*/ 
	ALTER TABLE TBL_PROJECT ADD CONSTRAINT FK_PROJECT_MEMBER FOREIGN KEY(MEMBER_ID)
	REFERENCES TBL_MEMBER(ID);
	
INSERT INTO WEGETHER.TBL_PROJECT
(ID, MEMBER_ID, PROJECT_TITLE, PROJECT_INTRODUCING, PROJECT_MAJOR, PROJECT_SCHOOL, PROJECT_REGISTER_DATE, PROJECT_UPDATE_DATE, PROJECT_END_DATE, PROJECT_READ_COUNT, PROJECT_NOW_PERSONNEL, PROJECT_TOTAL_PERSONNEL)
VALUES(SEQ_PROJECT.NEXTVAL, 41, '브랜드마케팅프로젝트', '브랜드마케팅을전문으로하는프로젝트입니다', '전공무관', '경희대학교', SYSDATE, SYSDATE, '2023-06-19', 2, 5, 10);

INSERT INTO WEGETHER.TBL_PROJECT
(ID, MEMBER_ID, PROJECT_TITLE, PROJECT_INTRODUCING, PROJECT_MAJOR, PROJECT_SCHOOL, PROJECT_REGISTER_DATE, PROJECT_UPDATE_DATE, PROJECT_END_DATE, PROJECT_READ_COUNT, PROJECT_NOW_PERSONNEL, PROJECT_TOTAL_PERSONNEL)
VALUES(SEQ_PROJECT.NEXTVAL, 41, 'SNS디자인및운영프로젝트', 'SNS디자인과 운영을 전문적으로 관리하고 만드는 프로젝트입니다', '전공무관', '고려대학교', SYSDATE, SYSDATE, '2023-06-19', 2, 2, 8);

INSERT INTO WEGETHER.TBL_PROJECT
(ID, MEMBER_ID, PROJECT_TITLE, PROJECT_INTRODUCING, PROJECT_MAJOR, PROJECT_SCHOOL, PROJECT_REGISTER_DATE, PROJECT_UPDATE_DATE, PROJECT_END_DATE, PROJECT_READ_COUNT, PROJECT_NOW_PERSONNEL, PROJECT_TOTAL_PERSONNEL)
VALUES(SEQ_PROJECT.NEXTVAL, 41, '영상제작및편집프로젝트', '영상을 제작하고 편집하는 것을 전문적으로 하는 프로젝트입니다', '영상관련전공', '중앙대학교', SYSDATE, SYSDATE, '2023-06-19', 2, 2, 8);

INSERT INTO WEGETHER.TBL_PROJECT
(ID, MEMBER_ID, PROJECT_TITLE, PROJECT_INTRODUCING, PROJECT_MAJOR, PROJECT_SCHOOL, PROJECT_REGISTER_DATE, PROJECT_UPDATE_DATE, PROJECT_END_DATE, PROJECT_READ_COUNT, PROJECT_NOW_PERSONNEL, PROJECT_TOTAL_PERSONNEL)
VALUES(SEQ_PROJECT.NEXTVAL, 41, '자소서첨삭및학업계획프로젝트', '자소서 첨삭 및 학업계획을 관리해주는 프로젝트입니다', '전공무관', '학력무관', SYSDATE, SYSDATE, '2023-06-19', 10, 15, 30);

INSERT INTO WEGETHER.TBL_PROJECT
(ID, MEMBER_ID, PROJECT_TITLE, PROJECT_INTRODUCING, PROJECT_MAJOR, PROJECT_SCHOOL, PROJECT_REGISTER_DATE, PROJECT_UPDATE_DATE, PROJECT_END_DATE, PROJECT_READ_COUNT, PROJECT_NOW_PERSONNEL, PROJECT_TOTAL_PERSONNEL)
VALUES(SEQ_PROJECT.NEXTVAL, 41, '예비고1을위한프로젝트', '앞으로의 학교생활 성공적인 고등학교 생활을 원하는 학생들을 위한 프로젝트입니다', '전공무관', '학력무관', SYSDATE, SYSDATE, '2023-07-19', 15, 20, 50);

INSERT INTO WEGETHER.TBL_PROJECT
(ID, MEMBER_ID, PROJECT_TITLE, PROJECT_INTRODUCING, PROJECT_MAJOR, PROJECT_SCHOOL, PROJECT_REGISTER_DATE, PROJECT_UPDATE_DATE, PROJECT_END_DATE, PROJECT_READ_COUNT, PROJECT_NOW_PERSONNEL, PROJECT_TOTAL_PERSONNEL)
VALUES(SEQ_PROJECT.NEXTVAL, 41, '초보자도가능한드로잉프로젝트', '드로잉을 배우시고 싶으신분들을 위한 프로젝트입니다', '전공무관', '학력무관', SYSDATE, SYSDATE, '2023-07-19', 10, 5, 15);

INSERT INTO WEGETHER.TBL_PROJECT
(ID, MEMBER_ID, PROJECT_TITLE, PROJECT_INTRODUCING, PROJECT_MAJOR, PROJECT_SCHOOL, PROJECT_REGISTER_DATE, PROJECT_UPDATE_DATE, PROJECT_END_DATE, PROJECT_READ_COUNT, PROJECT_NOW_PERSONNEL, PROJECT_TOTAL_PERSONNEL)
VALUES(SEQ_PROJECT.NEXTVAL, 41, '다이어트를위한프로젝트', '좋은 몸을 만드시고 싶으신가요? 여러분들을 위한 프로젝트입니다', '전공무관', '학력무관', SYSDATE, SYSDATE, '2023-06-19', 10, 25, 50);

INSERT INTO WEGETHER.TBL_PROJECT
(ID, MEMBER_ID, PROJECT_TITLE, PROJECT_INTRODUCING, PROJECT_MAJOR, PROJECT_SCHOOL, PROJECT_REGISTER_DATE, PROJECT_UPDATE_DATE, PROJECT_END_DATE, PROJECT_READ_COUNT, PROJECT_NOW_PERSONNEL, PROJECT_TOTAL_PERSONNEL)
VALUES(SEQ_PROJECT.NEXTVAL, 41, '노래를잘하고싶으신분들을위한프로젝트', '노래를 잘하고싶으신가요? 음치를 고치고 싶으신가요? 참여하세요', '전공무관', '학력무관', SYSDATE, SYSDATE, '2023-06-19', 10, 15, 30);

INSERT INTO WEGETHER.TBL_PROJECT
(ID, MEMBER_ID, PROJECT_TITLE, PROJECT_INTRODUCING, PROJECT_MAJOR, PROJECT_SCHOOL, PROJECT_REGISTER_DATE, PROJECT_UPDATE_DATE, PROJECT_END_DATE, PROJECT_READ_COUNT, PROJECT_NOW_PERSONNEL, PROJECT_TOTAL_PERSONNEL)
VALUES(SEQ_PROJECT.NEXTVAL, 41, '투자및트레이딩프로젝트', '투자를 잘 하고싶으신가요? 트레이딩을 배우고싶으신가요?', '전공무관', '학력무관', SYSDATE, SYSDATE, '2023-06-19', 50, 8, 10);

INSERT INTO WEGETHER.TBL_PROJECT
(ID, MEMBER_ID, PROJECT_TITLE, PROJECT_INTRODUCING, PROJECT_MAJOR, PROJECT_SCHOOL, PROJECT_REGISTER_DATE, PROJECT_UPDATE_DATE, PROJECT_END_DATE, PROJECT_READ_COUNT, PROJECT_NOW_PERSONNEL, PROJECT_TOTAL_PERSONNEL)
VALUES(SEQ_PROJECT.NEXTVAL, 41, '패션을알려드리는프로젝트', '옷을 어떻게 입어야할지 모르시나요? 패알못들을 위한 프로젝트가 왔습니다', '전공무관', '학력무관', SYSDATE, SYSDATE, '2023-06-19', 10, 15, 30);
