/*자료 파일 테이블 생성*/

CREATE SEQUENCE SEQ_DATA_FILE;

CREATE TABLE TBL_DATA_FILE(
	ID NUMBER CONSTRAINT PK_DATA_FILE PRIMARY KEY,
	DATA_ID NUMBER NOT NULL
);

SELECT * FROM TBL_DATA_FILE;

DROP TABLE TBL_DATA_FILE;

/*TBL_DATA_FILE 테이블 FK 설정*/
	ALTER TABLE TBL_DATA_FILE ADD CONSTRAINT FK_DATA_FILE_FILE FOREIGN KEY(ID)
	REFERENCES TBL_FILE(ID);

	ALTER TABLE TBL_DATA_FILE ADD CONSTRAINT FK_DATA_FILE_DATA FOREIGN KEY(DATA_ID)
	REFERENCES TBL_DATA(ID);