/*공지사항 테이블 생성*/

CREATE SEQUENCE SEQ_NOTICE;

CREATE TABLE TBL_NOTICE(
	ID NUMBER CONSTRAINT PK_NOTICE PRIMARY KEY,
	NOTICE_TITLE VARCHAR2(1000) NOT NULL,
	NOTICE_CONTENT VARCHAR2(1000) NOT NULL,
	NOTICE_REGISTER_DATE DATE DEFAULT SYSDATE,
	NOTICE_UPDATE_DATE DATE DEFAULT SYSDATE
);

SELECT * FROM TBL_NOTICE;

DROP TABLE TBL_NOTICE;