/*댓글 테이블 생성*/

CREATE SEQUENCE SEQ_REPLY;

CREATE TABLE TBL_REPLY(
	ID NUMBER CONSTRAINT PK_REPLY PRIMARY KEY,
	REPLY_CONTENT VARCHAR2(1000) NOT NULL,
	REPLY_GROUP NUMBER NOT NULL,
	REPLY_DEPTH NUMBER NOT NULL,
	REPLY_REGISTER_DATE DATE DEFAULT SYSDATE,
	REPLY_UPDATE_DATE DATE DEFAULT SYSDATE
);

SELECT * FROM TBL_REPLY;

DROP TABLE TBL_REPLY;

