/*포인트 테이블*/

CREATE SEQUENCE SEQ_POINT;

CREATE TABLE TBL_POINT(
	ID NUMBER CONSTRAINT PK_POINT PRIMARY KEY,
	MEMBER_ID NUMBER NOT NULL,
	DATA_ID NUMBER,
	POINT_HISTORY NUMBER NOT NULL,
	POINT_CATEGORY VARCHAR2(1000) NOT NULL CONSTRAINT CHECK_POINT_CATEGORY CHECK(POINT_CATEGORY IN('사용','적립')),
	POINT_RECORD_DATE DATE DEFAULT SYSDATE
);

SELECT * FROM TBL_POINT;

DROP TABLE TBL_POINT;

/*TBL_POINT 테이블 FK 설정*/
	ALTER TABLE TBL_POINT ADD CONSTRAINT FK_POINT_MEMBER FOREIGN KEY(MEMBER_ID)
	REFERENCES TBL_MEMBER(ID);
	
	ALTER TABLE TBL_POINT ADD CONSTRAINT FK_POINT_DATA FOREIGN KEY(DATA_ID)
	REFERENCES TBL_DATA(ID);