/*상담 테이블 생성*/

CREATE SEQUENCE SEQ_CONSULTING;

CREATE TABLE TBL_CONSULTING(
	ID NUMBER CONSTRAINT PK_CONSULTING PRIMARY KEY,
	MEMBER_ID NUMBER NOT NULL,
	CONSULTING_TITLE VARCHAR2(1000) NOT NULL,
	CONSULTING_CONTENT VARCHAR2(1000) NOT NULL,
	CONSULTING_CATEGORY VARCHAR2(1000) NOT NULL,
	CONSULTING_REGISTER_DATE DATE DEFAULT SYSDATE,
	CONSULTING_UPDATE_DATE DATE DEFAULT SYSDATE
);

SELECT * FROM TBL_CONSULTING;

DROP TABLE TBL_CONSULTING;

/*TBL_CONSULTING 테이블 FK 설정*/
	ALTER TABLE TBL_CONSULTING ADD CONSTRAINT FK_CONSULTING_MEMBER FOREIGN KEY(MEMBER_ID)
	REFERENCES TBL_MEMBER(ID);